### Get All
GET https://cse341-project1-0cba.onrender.com/contacts/


### Get by Id
GET https://cse341-project1-0cba.onrender.com/contacts/66f2ea68f4056295852bc913


### Create
POST https://cse341-project1-0cba.onrender.com/contacts/ HTTP/1.1
content-Type: application/json

{
    "birthday": "2022-08-02T00:00:00.000Z",
    "email": "Emma.vega@gmail.com",
    "favoriteColor": "Purple",
    "firstName": "Emma",
    "lastName": "Vega"
}

### Update
PUT https://cse341-project1-0cba.onrender.com/contacts/66f2ea68f4056295852bc913 HTTP/1.1
content-Type: application/json

{
    "birthday": "2000-01-07T00:00:00.000Z",
    "email": "fredy.vega@gmail.com",
    "favoriteColor": "Red",
    "firstName": "Fredy",
    "lastName": "Vega"
}



### Delete by Id
DELETE https://cse341-project1-0cba.onrender.com/contacts/66f5da7a5bc1e379716cc3a3
